vars: {
        d2-config: {
          layout-engine: elk
            theme-id: 6
        }
      }

title: |md
### No time to breath 
| {
shape: text
         near: top-center
         style.font-size: 35
         style.underline: true
}

*.style.font-size: 14
*.style.shadow: true

#direction: right

No Time\nTo Breath -> Rushed Decision Making: increases {
  style.animated: true
    style.bold: true
}
Rushed Decision Making -> Group Thinking, Authority Wins : increases {
  style.animated: true
    style.bold: true
}
Group Thinking, Authority Wins -> Brown compromise : increases {
  style.animated: true
    style.bold: true
}
Brown compromise -> No Time\nTo Breath : Team is reactive\n Want to ship fast {
  style.animated: true
    style.bold: true
}


