vars: {
        d2-config: {
          layout-engine: elk
            theme-id: 6
        }
      }

title: |md
### Positive loop: clear success definition
| {
shape: text
         near: top-center
         style.font-size: 40
         style.underline: true
}

*.style.font-size: 14
*.style.shadow: true

#direction: right

Well Defined Success Criteria -> Objective Decision Handling Criteria: increases {
  style.animated: true
    style.bold: true
}
Objective Decision Handling Criteria -> Success and Failure can be measured: increases {
  style.animated: true
    style.bold: true
}
Success and Failure can be measured -> Learnings : increases {
  style.animated: true
    style.bold: true
}
Learnings -> Well Defined Success Criteria: success easier to define {
  style.animated: true
    style.bold: true
}


