vars: {
        d2-config: {
          layout-engine: elk
            theme-id: 6
        }
      }

title: |md
### Negative loop: no success definition
| {
shape: text
         near: top-center
         style.font-size: 40
         style.underline: true
}

*.style.font-size: 14
*.style.shadow: true

#direction: right

No Success Criteria -> No way\n to decide objectively : increases {
  style.animated: true
    style.bold: true
}
No way\n to decide objectively ->Group Thinking, Authority : increases {
  style.animated: true
    style.bold: true
}
Group Thinking, Authority -> Brown compromise : increases {
  style.animated: true
    style.bold: true
}
Brown compromise -> No Success Criteria : No Measure of Success\n Success harder to define {
  style.animated: true
    style.bold: true
}

