vars: {
        d2-config: {
          layout-engine: elk
            theme-id: 6
        }
      }

title: |md
### Negative loop: lack of ownership
| {
shape: text
         near: top-center
         style.font-size: 40
         style.underline: true
}

*.style.font-size: 14
*.style.shadow: true

#direction: right

No Single Threaded Ownership -> No Ownership : increases {
  style.animated: true
    style.bold: true
}
No Ownership -> Pleasing others, Group Thinking, Authority : increases {
  style.animated: true
    style.bold: true
}
Pleasing others, Group Thinking, Authority -> Brown compromise : increases {
  style.animated: true
    style.bold: true
}
Brown compromise -> No Single Threaded Ownership : increases {
  style.animated: true
    style.bold: true
}
