vars: {
  d2-config: {
    layout-engine: elk
    theme-id: 6
  }
}

title: |md
  ### Positive Loop: Single-threaded ownership
| {
  shape: text
  near: top-center
  style.font-size: 40
  style.underline: true
}

*.style.font-size: 14
*.style.shadow: true

Single Threaded Owner -> Clear Ownership : increases {
  style.animated: true
  style.bold: true
}
Clear Ownership -> Clear trade offs : increases {
  style.animated: true
style.bold: true
}
Clear trade offs -> Well understood decision : increases {
  style.animated: true
style.bold: true
}
Well understood decision -> Single Threaded Owner: increases {
  style.animated: true
   style.bold: true
}
